/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedGateRouteImport } from './routes/_authenticated/gate'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedLotsIndexRouteImport } from './routes/_authenticated/lots/index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsAuditRouteImport } from './routes/_authenticated/settings/audit'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedLotsLotIdRouteImport } from './routes/_authenticated/lots/$lotId'
import { Route as AuthenticatedDriversDriverIdRouteImport } from './routes/_authenticated/drivers/$driverId'
import { Route as AuthenticatedLotsLotIdMapRouteImport } from './routes/_authenticated/lots/$lotId_.map'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGateRoute = AuthenticatedGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLotsIndexRoute = AuthenticatedLotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAuditRoute =
  AuthenticatedSettingsAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedLotsLotIdRoute = AuthenticatedLotsLotIdRouteImport.update({
  id: '/lots/$lotId',
  path: '/lots/$lotId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversDriverIdRoute =
  AuthenticatedDriversDriverIdRouteImport.update({
    id: '/drivers/$driverId',
    path: '/drivers/$driverId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLotsLotIdMapRoute =
  AuthenticatedLotsLotIdMapRouteImport.update({
    id: '/lots/$lotId_/map',
    path: '/lots/$lotId/map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/gate': typeof AuthenticatedGateRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/lots/$lotId': typeof AuthenticatedLotsLotIdRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/drivers/': typeof AuthenticatedDriversIndexRoute
  '/lots/': typeof AuthenticatedLotsIndexRoute
  '/lots/$lotId/map': typeof AuthenticatedLotsLotIdMapRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/gate': typeof AuthenticatedGateRoute
  '/': typeof AuthenticatedIndexRoute
  '/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/lots/$lotId': typeof AuthenticatedLotsLotIdRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/lots': typeof AuthenticatedLotsIndexRoute
  '/lots/$lotId/map': typeof AuthenticatedLotsLotIdMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/gate': typeof AuthenticatedGateRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/drivers/$driverId': typeof AuthenticatedDriversDriverIdRoute
  '/_authenticated/lots/$lotId': typeof AuthenticatedLotsLotIdRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/audit': typeof AuthenticatedSettingsAuditRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/lots/': typeof AuthenticatedLotsIndexRoute
  '/_authenticated/lots/$lotId_/map': typeof AuthenticatedLotsLotIdMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/gate'
    | '/drivers/$driverId'
    | '/lots/$lotId'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/users'
    | '/drivers/'
    | '/lots/'
    | '/lots/$lotId/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/gate'
    | '/'
    | '/drivers/$driverId'
    | '/lots/$lotId'
    | '/settings/api-keys'
    | '/settings/audit'
    | '/settings/users'
    | '/drivers'
    | '/lots'
    | '/lots/$lotId/map'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/gate'
    | '/_authenticated/'
    | '/_authenticated/drivers/$driverId'
    | '/_authenticated/lots/$lotId'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/audit'
    | '/_authenticated/settings/users'
    | '/_authenticated/drivers/'
    | '/_authenticated/lots/'
    | '/_authenticated/lots/$lotId_/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gate': {
      id: '/_authenticated/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof AuthenticatedGateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lots/': {
      id: '/_authenticated/lots/'
      path: '/lots'
      fullPath: '/lots/'
      preLoaderRoute: typeof AuthenticatedLotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/audit': {
      id: '/_authenticated/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AuthenticatedSettingsAuditRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/lots/$lotId': {
      id: '/_authenticated/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/lots/$lotId'
      preLoaderRoute: typeof AuthenticatedLotsLotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers/$driverId': {
      id: '/_authenticated/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof AuthenticatedDriversDriverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lots/$lotId_/map': {
      id: '/_authenticated/lots/$lotId_/map'
      path: '/lots/$lotId/map'
      fullPath: '/lots/$lotId/map'
      preLoaderRoute: typeof AuthenticatedLotsLotIdMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAuditRoute: typeof AuthenticatedSettingsAuditRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
    AuthenticatedSettingsAuditRoute: AuthenticatedSettingsAuditRoute,
    AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedGateRoute: typeof AuthenticatedGateRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDriversDriverIdRoute: typeof AuthenticatedDriversDriverIdRoute
  AuthenticatedLotsLotIdRoute: typeof AuthenticatedLotsLotIdRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedLotsIndexRoute: typeof AuthenticatedLotsIndexRoute
  AuthenticatedLotsLotIdMapRoute: typeof AuthenticatedLotsLotIdMapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedGateRoute: AuthenticatedGateRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDriversDriverIdRoute: AuthenticatedDriversDriverIdRoute,
  AuthenticatedLotsLotIdRoute: AuthenticatedLotsLotIdRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedLotsIndexRoute: AuthenticatedLotsIndexRoute,
  AuthenticatedLotsLotIdMapRoute: AuthenticatedLotsLotIdMapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
